# Generated by Django 3.1.3 on 2020-12-10 13:40

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCircuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
